# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import perfil.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='alias',
            field=models.CharField(default=perfil.models.unique_rand, max_length=30, unique=True),
        ),
    ]
