# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import perfil.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20180728_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='alias',
            field=models.CharField(default=perfil.models.unique_rand, error_messages={'unique': 'Ya existe un perfil con este Alias'}, max_length=30, unique=True),
        ),
    ]
