# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-04 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0033_debate_num_rebate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0003_auto_20180728_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=False)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
