# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-05 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_usuario',
        ),
    ]
