# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_remove_notificacion_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
