# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-05 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20180805_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_debate',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
