# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0033_debate_num_rebate'),
        ('perfil', '0007_auto_20180805_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=300)),
                ('estado', models.IntegerField(default=0)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
            ],
        ),
    ]
