# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_auto_20180916_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='img',
            field=models.FileField(blank=True, default='RDdefault.png', null=True, upload_to=b''),
        ),
    ]
