# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-16 03:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumen', '0025_auto_20180716_0322'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Argumento',
            fields=[
                ('id_argumento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('postura', models.IntegerField(default=1)),
                ('alias_c', models.CharField(default='username', max_length=50)),
                ('date_argumento', models.DateField(default=datetime.datetime.now)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id_edicion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_edicion', models.CharField(max_length=300)),
                ('date_edicion', models.DateTimeField(default=datetime.datetime.now)),
                ('id_argumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.Argumento')),
            ],
        ),
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id_postura', models.AutoField(primary_key=True, serialize=False)),
                ('postura', models.IntegerField(default=1)),
                ('date_Postura', models.DateField(default=datetime.datetime.now)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('alias_c', models.CharField(default='username', max_length=50)),
                ('date_respuesta', models.DateField(default=datetime.datetime.now)),
                ('id_argumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.Argumento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('date_valoracion', models.DateField(default=datetime.datetime.now)),
                ('id_argumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.Argumento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
