# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20180924_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
