# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_edicion_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='tipo_valoracion',
            field=models.CharField(default='nulo', max_length=50),
        ),
    ]
