# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-23 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_valoracion_tipo_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postura',
            name='postura_inicial',
            field=models.IntegerField(default=1),
        ),
    ]
