# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-23 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_postura_postura_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postura',
            name='cambio_postura',
            field=models.CharField(default='vacio', max_length=50),
        ),
    ]
