# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-12 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_auto_20180723_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postura',
            name='postura_inicial',
        ),
    ]
