# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0007_remove_postura_postura_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postura',
            name='cuenta_cambios',
            field=models.IntegerField(default=0),
        ),
    ]
