# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0037_debate_tipo_participacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0009_argumento_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
