# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0038_auto_20180902_0238'),
        ('debate', '0010_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
            ],
        ),
    ]
