# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id_debate', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('estado', models.CharField(default='abierto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Usuario'),
        ),
    ]
