# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id_postura', models.AutoField(primary_key=True, serialize=False)),
                ('postura', models.NullBooleanField()),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Usuario')),
            ],
        ),
    ]
