# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='estado',
            field=models.CharField(default='abierto', max_length=20),
        ),
    ]
