# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='owner',
            new_name='id_user',
        ),
    ]
