# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0004_auto_20161124_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postura',
            name='postura',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
