# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumen', '0006_auto_20161124_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argumento',
            fields=[
                ('id_argumento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('id_debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Debate')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
