# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0007_argumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumento',
            name='postura',
            field=models.IntegerField(default=1),
        ),
    ]
