# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('resumen', '0009_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alias', models.CharField(default='anonimo', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='debate',
            name='alias_c',
            field=models.CharField(default='False', max_length=50),
        ),
        migrations.AddField(
            model_name='debate',
            name='date_fin',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='debate',
            name='largo',
            field=models.IntegerField(blank=True, default=300),
        ),
    ]
