# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0010_auto_20161207_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
