# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0011_auto_20161208_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='alias_c',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
