# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumen', '0013_argumento_alias_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.IntegerField(max_length=300)),
                ('id_argumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Argumento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
