# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0014_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
