# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0016_respuesta_alias_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id_edicion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_edicion', models.CharField(max_length=300)),
                ('date_edicion', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='argumento',
            name='date_argumento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='postura',
            name='date_Postura',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='date_respuesta',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='date_valoracion',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='edicion',
            name='id_argumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.Argumento'),
        ),
    ]
