# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0019_auto_20170111_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicion',
            name='date_edicion',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
