# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0021_auto_20170111_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumento',
            name='usa_alias',
            field=models.BooleanField(default=False),
        ),
    ]
