# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-16 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0024_perfil_reputacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumento',
            name='id_debate',
        ),
        migrations.RemoveField(
            model_name='argumento',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='edicion',
            name='id_argumento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postura',
            name='id_debate',
        ),
        migrations.RemoveField(
            model_name='postura',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='id_argumento',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='id_argumento',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Argumento',
        ),
        migrations.DeleteModel(
            name='Edicion',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Postura',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
