# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0025_auto_20180716_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
