# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-25 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0026_debate_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='img',
        ),
    ]
