# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0027_remove_debate_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
