# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0028_debate_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.FileField(upload_to='/media/')),
            ],
        ),
    ]
