# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0031_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AlterField(
            model_name='debate',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
