# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-27 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0032_auto_20180727_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='num_rebate',
            field=models.IntegerField(default=1),
        ),
    ]
