# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-12 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0034_auto_20180812_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='tipo_rebate',
            field=models.IntegerField(default=0),
        ),
    ]
