# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 23:49
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resumen', '0035_debate_tipo_rebate'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
