# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0037_debate_tipo_participacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='debate',
            name='num_cambio_postura',
            field=models.IntegerField(default=3),
        ),
    ]
